### ISSUE TITLE
Can't pickle MagicMock or Mock

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#139]
```
This is because a MagicMock instance has a custom MagicMock subclass.

{{{
>>> from pickle import dumps
>>> from mock import MagicMock
>>> dumps(MagicMock())
Traceback (most recent call last):
  ...
pickle.PicklingError: Can't pickle <class 'mock.MagicMock'>: it's not the same 
object as mock.MagicMock
}}}

```

Original issue reported on code.google.com by `fuzzyman` on 8 Mar 2012 at 6:17

**Comment by sprt** [comment]
Any workaround?

**Comment by sprt** [comment]
This works for my use case:

```python
class PickableMock(Mock):
    def __reduce__(self):
        return (Mock, ())
```

**Comment by rbtcollins** [comment]
Upstreamed as http://bugs.python.org/issue14577 and http://bugs.python.org/issue20804

If there are more issues needed, please file them as bugs on bugs.python.org. {This tracker is focusing on bugs unique to the backport}
