### ISSUE TITLE
No way to assert call not made

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#159]
```
There is currently no way to assert that a specific call has not been made. The 
workaround would be something like self.assertNotRaises(AssertionError, 
mock.assert_any_call(..._)) which is a bit awkward to write.

I can see two possible syntaxes:

1. self.assertTrue(not mock.has_any_call(....))
2. mock.assert_no_call_with(...)



```

Original issue reported on code.google.com by `wich...@outlook.com` on 17 May 2012 at 12:00

**Comment by rbtcollins** [comment]
See also #243

**Comment by rbtcollins** [comment]
This needs to be migrated upstream

**Comment by rbtcollins** [comment]
On balance, I think the assertNotIn(...) and AssertEqual([], mock.calls) are sufficient and give good enough error messages. If someone wants something better please open a bug on the python bug tracker.
