### ISSUE TITLE
Link to mockstar in the docs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#179]
```
http://mockstar.readthedocs.org/en/latest/index.html
```

Original issue reported on code.google.com by `fuzzyman` on 28 Sep 2012 at 10:37

**Comment by berkerpeksag** [comment]
I think we can close this one:

* The main docs are now at docs.python.org and we don't add such links if they don't replace or do a better job than a stdlib module (e.g. urllib/requests)
* The last commit is dated to 2013: https://bitbucket.org/k_bx/mockstar/commits/all
* It doesn't look like a popular project: 883 downloads in the last month https://pypi.python.org/pypi/mockstar
