### ISSUE TITLE
side_effects iterator does not honor sentinel.DEFAULT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#190]
```
What steps will reproduce the problem?
A mock with a return_value and a side_effects iterable will not return the 
given return_value when the side_effect is DEFAULT.
From the attached patch:

mock = Mock(return_value=2)
mock.side_effect = iter([1, DEFAULT])
self.assertEqual([mock(), mock()], [1, 2])

What is the expected output? What do you see instead?
When side_effect is an iterable and one item is sentinel.DEFAULT the 
corresponding call to the mock should return the return_value given in the mock 
constructor. Instead it returns sentinel.DEFAULT.

What version of the product are you using? On what operating system?
Tested with changeset 950:63c726990a85.

Please provide any additional information below.
The attached patch includes a test case and a fix.
```

Original issue reported on code.google.com by `oseem...@gmail.com` on 22 Nov 2012 at 9:42

Attachments:
* [mock.patch](https://storage.googleapis.com/google-code-attachments/mock/issue-190/comment-0/mock.patch)

**Comment by kparal** [comment]
Hello, I just got bitten by this. I wrote a patch, and then found out that the bug is already reported and exactly the same patch is already attached. Could we please commit this?

**Comment by rbtcollins** [comment]
Hi - this should be done on CPython (where mock is now developed). From there we can backport it into the mock distribution. https://bugs.python.org/. If you wanted to post your patch there, that would be a great step forward.

**Comment by kparal** [comment]
Hello, this is fixed in Python 3 (I tested 3.4.3). Only Python 2 version is broken. Since mock is not present in Python 2 standard library, should I still report the bug at https://bugs.python.org/? It seems to me that the fix for Python 2 should occur here.

**Comment by rbtcollins** [comment]
Looks solved to me:
```
>>> import mock
>>> m = mock.Mock(return_value=2)
>>> m.side_effect = iter([1, mock.DEFAULT])
>>> [m(), m()]
[1, 2]
```

**Comment by kparal** [comment]
Yes, I was using an older version, sorry. It is fixed and can be closed.
