### ISSUE TITLE
Patch for /docs/patch.txt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#211]
```
minor typo fix in documentation
```

Original issue reported on code.google.com by `boscomut...@gmail.com` on 1 Aug 2013 at 12:26

Attachments:
* [patch.txt.patch](https://storage.googleapis.com/google-code-attachments/mock/issue-211/comment-0/patch.txt.patch)

**Comment by rbtcollins** [comment]
We've deleted the local docs in favour of the reference docs.
