### ISSUE TITLE
Patch for /mock.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#215]
```
Typo in doc string for function, patch().
```

Original issue reported on code.google.com by `nerd.b...@gmail.com` on 22 Oct 2013 at 12:13

Attachments:
* [mock.py.patch](https://storage.googleapis.com/google-code-attachments/mock/issue-215/comment-0/mock.py.patch)

**Comment by rbtcollins** [comment]
Applied to cpython, thank you.
