### ISSUE TITLE
Require unittest.mock with Python >=3.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#223]
```
mock is incompatible with Python 3.4 (32 errors in test suite of mock).

Unfortunately some projects use:
  import mock
instead of:
  try:
      from unittest import mock
  except ImportError:
      import mock

I suggest that mock require using unittest.mock with Python >=3.3. I attach 
patch for mock.
```

Original issue reported on code.google.com by `Arfrever...@gmail.com` on 6 Mar 2014 at 7:56

Attachments:
* [mock.patch](https://storage.googleapis.com/google-code-attachments/mock/issue-223/comment-0/mock.patch)

**Comment by rbtcollins** [comment]
We've fixed the incompat issue, but thanks anyhow.
