### ISSUE TITLE
deepcopying property of mock with spec breaks mocked calls

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#235]
```
What steps will reproduce the problem?
1. Execute the attached script
2. Watch in horror
3. ???
4. Profit

What is the expected output? What do you see instead?
Assertion in line 14 should pass, instead I get the following exception:
Traceback (most recent call last):
  File "mock_error.py", line 14, in <module>
    assert 1 == copy.nested_property()
  File "/home/sir/.virtualenvs/issue/local/lib/python2.7/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/sir/.virtualenvs/issue/local/lib/python2.7/site-packages/mock.py", line 997, in _mock_call
    _new_parent.mock_calls.append(this_mock_call)
AttributeError: 'TestClass' object has no attribute 'mock_calls'

What version of the product are you using? On what operating system?
mock==1.0.1
python==2.7.3
ubuntu precise (Ubuntu 12.04.4 LTS)

Please provide any additional information below.


```

Original issue reported on code.google.com by `heidarli...@gmail.com` on 11 Jul 2014 at 1:54

Attachments:
- [mock_error.py](https://storage.googleapis.com/google-code-attachments/mock/issue-235/comment-0/mock_error.py)

**Comment by dimaqq** [comment]
Why would `deepcopy()` also copy attributes of generic (unknown) type?

I think I'm missing something here.

**Comment by rbtcollins** [comment]
Someone needs to validate this on current mock and see if its still relevant / sane. Note that its an imported bug from google code, so we don't know who actually filed it in the first place.

**Comment by joguSD** [comment]
Ran into a similar issue today using Python 2.7.13 and mock 2.0.0. 
```
>>> class Test(object):
...     field = 2

>>> import mock

>>> import copy

>>> m = mock.Mock(spec=Test)

>>> copy.copy(m)
<__main__.Test object at 0x10bd9e210> # copy is a real instance

>>> m
<Mock spec='Test' id='4495109136'>
```

This does not happen on Python 3.

**Comment by cjw296** [comment]
@joguSD - This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
