### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#240]
```
The same check and assignment will be made a few lines later anyway, so this 
code can be removed without any change in the behavior.
```

Original issue reported on code.google.com by `sb...@google.com` on 17 Dec 2014 at 7:27

Attachments:
* [mock.py.patch](https://storage.googleapis.com/google-code-attachments/mock/issue-240/comment-0/mock.py.patch)

**Comment by rbtcollins** [comment]
This was applied upstream at some point.
