### ISSUE TITLE
Include wheels on the PyPI distribution

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#246]
```
It would be great if the PyPI distribution could contain wheels as well as the 
source distributions, which would make pip install mock slightly faster.
```

Original issue reported on code.google.com by `ARPl...@gmail.com` on 16 Feb 2015 at 1:40

**Comment by rbtcollins** [comment]
I do. There isn't one for 1.1.1 because of a bug in pbr, but the next point release will have a wheel.
