### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by rchrom** [testing-cabal/mock#259]
test/mymock.py:3: in <module>
    from mock import Mock, patch
.tox/py26/lib/python2.6/site-packages/mock/__init__.py:2: in <module>
    import mock.mock as _mock
E     File "/tmp/.tox/py26/lib/python2.6/site-packages/mock/mock.py", line 132
E       _builtins = {name for name in dir(builtins) if not name.startswith('_')}
E                           ^
E   SyntaxError: invalid syntax

**Comment by rbtcollins** [comment]
Mock 1.1.0 does not support Python 2.6 This is in the docs (https://github.com/testing-cabal/mock/blob/master/docs/index.txt#L109) and reflected in the trove classifiers too.
