### ISSUE TITLE
assert_has_calls(foo) used to work, now doesn't

### ISSUE THREAD

**Issue by sdague** [testing-cabal/mock#263]
m.assert_has_calls(foo) used to work, but now fails violently if not specified as m.assert_has_calls([foo]).

The old behavior was nicer UX (given that this is often called with only a single value, at least in openstack code), and it would be nice to still support if possible.

If not it would be really good to include detailed release notes about this change.

**Comment by rbtcollins** [comment]
@sdague can you whip up a small reproducer example? I'm happy to go track this down and fix in cPython if it is there, but I'm not entirely sure what you were doing before vs now.

**Comment by rbtcollins** [comment]
This is I think related to #243 - in that assert_has_calls(foo) where foo is a [], is at best ambiguous.
