### ISSUE TITLE
mock.patch.object ... autospec=True does not work

### ISSUE THREAD

**Issue by sdague** [testing-cabal/mock#264]
def test_serialized_with_retry_socket_reset_reraised(self):
        exc = socket.error()
        exc.errno = errno.ECONNRESET
        plugin = 'glance'
        fn = 'download_vhd'
        num_retries = 1
        callback = None
        retry_cb = mock.Mock()
        with mock.patch.object(self.session, 'call_plugin_serialized',
                autospec=True) as call_plugin_serialized:
            call_plugin_serialized.side_effect = exc
            self.assertRaises(exception.PluginRetriesExceeded,
                    self.session.call_plugin_serialized_with_retry, plugin, fn,
                    num_retries, callback, retry_cb)
            call_plugin_serialized.assert_called_with(plugin, fn)
            self.assertEqual(2, call_plugin_serialized.call_count)

From https://github.com/openstack/nova/blob/master/nova/tests/unit/virt/xenapi/client/test_session.py#L143-L158

No longer works. 

The current work around is change 'autospec' to 'spec'. Not sure the root issue, lifeless sorted out the fix. This bug is here for tracking the resolution.

**Comment by divius** [comment]
Here is my reproducer for the failure: http://fpaste.org/242638/
Note that with spec=True method signature is not checked, so it's not literal replacement.

I was told by someone that the same regression happened between Python 3.4.0 and 3.4.2.

**Comment by rbtcollins** [comment]
This was reported upstream as http://bugs.python.org/issue23661 and I'm applying the patch and backporting now.

**Comment by rbtcollins** [comment]
Fixed in Python 3.6 and in mock 1.1.3 [backwards compat bugfix].
