### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by sssilver** [testing-cabal/mock#270]
This started happening after the latest release on the latest Python 2:

```
  Running setup.py install for mock
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-VRYOyE/mock/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bke1Cs-record/install-record.txt --single-version-externally-managed --compile:
    error in setup command: Invalid environment marker: python_version<"3" or python_version>="3.3"
```

**Comment by systemizer** [comment]
I ran into the same issue. You need to upgrade setuptools to fix the issue. It looks mock is using a newer syntax of setuptools metadata that is not backward compatible with your version of setuptools.

Before, I was running setuptools 12.0.5. After upgrading to 18.0.1 everything appears to be happy.

To determine which version of setuptools you are running you can run:

    python -c "import setuptools; print setuptools.version.__version__"

**Comment by systemizer** [comment]
I've created a pull request to fix this issue:

https://github.com/testing-cabal/mock/pull/272

Relevant details: https://pythonhosted.org/setuptools/history.html#id5

**Comment by rbtcollins** [comment]
Dup of #261
