### ISSUE TITLE
1.1.3 fails to install on Ubuntu 13.10, Python 2.7.5+

### ISSUE THREAD

**Issue by aaronfay** [testing-cabal/mock#279]
I couldn't install the latest release this morning on one of my servers:
```
Downloading/unpacking mock (from my-package==0.2.6)
  Downloading mock-1.1.3.tar.gz (70kB): 70kB downloaded
  Running setup.py egg_info for package mock
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/bamboo/.virtualenvs/my-package/build/mock/setup.py", line 10, in <module>
        setuptools_installed = StrictVersion(setuptools.version.__version__)
    AttributeError: 'module' object has no attribute 'version'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/bamboo/.virtualenvs/my-package/build/mock/setup.py", line 10, in <module>

    setuptools_installed = StrictVersion(setuptools.version.__version__)

AttributeError: 'module' object has no attribute 'version'

----------------------------------------
Cleaning up...
```

**Versions**
```
(my-env)super-server:~/$ python --version
Python 2.7.5+
(my-env)super-server:~/$ virtualenv --version
1.10.1
(my-env)super-server:~/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 13.10
Release:	13.10
Codename:	saucy
```

Let me know if you need more details.

Thanks,

**Comment by tehsphinx** [comment]
Have the same issue on:
- Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-15) )
- Python 2.7.3

**Comment by rpratte** [comment]
Same for:

(venv)-bash-4.1$ python --version
Python 2.7.5
(venv)-bash-4.1$ virtualenv --version
1.12.dev1
(venv)-bash-4.1$ lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	Scientific
Description:	Scientific Linux release 6.1 (Carbon)
Release:	6.1
Codename:	Carbon

**Comment by rpratte** [comment]
Actually, updating my version of setuptools fixed this issue.

**Comment by rbtcollins** [comment]
Yes, I think the patch to detect setuptools version was itself not compatible with older setuptools. I"ll have a fiddle today and see if I can make something better. Otherwise I think we're probably going to have to use a setup_requires on setuptools, which will not work but might give more meaningful errors.

**Comment by pypingou** [comment]
Any possibility to have a bug-fix release with this commit?
