### ISSUE TITLE
Colissions with mock for open builtins in 1.1.3

### ISSUE THREAD

**Issue by andreykurilin** [testing-cabal/mock#280]
We have a base TestCase with simple test and one inheritor(see below). When inheritor and TestCase are launched by one worker, the mock_open is getting torn down after it's first use, and not correctly built again(returns empty string) on subsequent calls.

    import mock
    import six
    import testtools

    class TestCase(testtools.TestCase):
        @mock.patch.object(six.moves.builtins, 'open', mock.mock_open(read_data='FAKE_DATA'))
        def test_check_open(self):
            with open("some") as f:
                self.assertEqual('FAKE_DATA', f.read())

    class AnotherTestCase(TestCase):
        pass

**Comment by rbtcollins** [comment]
Passes on 3.6 like so:
import builtins
...
    @patch.object(builtins, 'open', mock.mock_open(read_data='FAKE_DATA'))
    def test_check_open(self):
        with open("some") as f:
            self.assertEqual('FAKE_DATA', f.read())

or like
    @patch('builtins.open', mock.mock_open(read_data='FAKE_DATA'))
    def test_check_open(self):
        with open("some") as f:
            self.assertEqual('FAKE_DATA', f.read())

**Comment by rbtcollins** [comment]
This is http://bugs.python.org/issue21750 - please fix there.

**Comment by rbtcollins** [comment]
I've put a patch up there for consideration. If its got no reviews by next week I'll just land it.

**Comment by rbtcollins** [comment]
Fixed in 1.1.4
