### ISSUE TITLE
Mock call assertion fails in 1.1.x

### ISSUE THREAD

**Issue by miki725** [testing-cabal/mock#283]
Im experiencing a very strange issue with `mock>=1.1` which causes mock call assertion to fail in one of my projects:

``` python
1) FAIL: test_map_node_expression (tests.test_mapper.TestMapperBase)

   Traceback (most recent call last):
    /Volumes/Data/Users/miki725/.virtualenvs/simplepath/lib/python3.4/site-packages/mock/mock.py line 1299 in patched
      return func(*args, **keywargs)
    tests/test_mapper.py line 365 in test_map_node_expression
      context=mock_get_lookup_context.return_value,
    /Volumes/Data/Users/miki725/.virtualenvs/simplepath/lib/python3.4/site-packages/mock/mock.py line 942 in assert_called_once_with
      return self.assert_called_with(*args, **kwargs)
    /Volumes/Data/Users/miki725/.virtualenvs/simplepath/lib/python3.4/site-packages/mock/mock.py line 931 in assert_called_with
      six.raise_from(AssertionError(_error_message(cause)), cause)
    <string> line 2 in raise_from

   AssertionError: Expected call: mock(sentinel.data, context=<MagicMock name='get_lookup_context()' id='4486874112'>, lut=sentinel.lut, super_root=sentinel.root)
   Actual call: mock(sentinel.data, context=<MagicMock name='get_lookup_context()' id='4486874112'>, lut=sentinel.lut, super_root=sentinel.root)
```

If you take a look at the assertion error, both calls are actually identical so the mock somehow cant detect that even though it prints identical mock calls in the assertion message.

Test passes perfectly on `mock==1.0.x` versions but something in `mock>=1.1.x` causes the test to fail. I tried to replicate the bug by using a dummy example however so far have not been successful. Due to that I cant produce a simple test case which could be included in mock test suite itself and so Ill try to provide all the information I can here and hopefully somebody can either spot what Im doing wrong or confirm the validity of a bug in mock itself.

In order to illustrate the issue better, I setup two branches (below are links to their PRs) in my project:
- [`lists`](https://github.com/dealertrack/simplepath/pull/6) - my feature branch where mock is pinned to `1.0.1` and all tests pass
- [`mock`](https://github.com/dealertrack/simplepath/pull/7) - branch where I pinned mock to `1.1.3` which causes same tests to fail both locally and in travis.

You can in open [mock->lists PR]([`mock`]%28https://github.com/dealertrack/simplepath/pull/7%29) that the only difference is the mock version makes me believe that mock might contain a bug.

Here are corresponding travis jobs for both branches (links to Py3 build however same happens on Py2 as well):
- [`lists`](https://travis-ci.org/dealertrack/simplepath/jobs/71019286) - tests pass
- [`mock`](https://travis-ci.org/dealertrack/simplepath/jobs/71019338) - tests fail

For convenience here are relevant links to code:
- [test case](https://github.com/dealertrack/simplepath/blob/mock/tests/test_mapper.py#L142-L154)
- [method test case is testing](https://github.com/dealertrack/simplepath/blob/mock/simplepath/mapper.py#L310-L311)

Any ideas?

Let me know if you will need any additional information to debug this further.

---

PS. I had similar results when trying to use Python3 built-in `unittest.mock`.

**Comment by rbtcollins** [comment]
That certainly is odd. I don't suppose you can boil it down to a more pithy example?

**Comment by miki725** [comment]
No. So far was unsuccessful in making a dummy example with the same failure.

**Comment by QuLogic** [comment]
How's this?
```
import mock
#from unittest import mock
import warnings

print(mock.__version__)

def bar():
    print('bar was called.')
    return 1

def foo():
    return bar()

print(foo())

with mock.patch('__main__.bar') as pb:
    print(foo())

pb.assert_called()
```

With mock 1.0.1, the test passes. With mock 1.1.3, the assert fails. With Python 3.4.3 (and altered import), the test passes.

**Comment by rbtcollins** [comment]
This fails on Python 3.5/3.6. Filing upstream

**Comment by rbtcollins** [comment]
Oh, actually no. @QuLogic your reproducer shows the confusing API - assert_called never existed. The assertion you're seeing is mock detecting you're trying to call an assertion that never existed and failing. 

This doesn't tell us anything about @miki725 's failure - sorry.

**Comment by QuLogic** [comment]
Huh, well at least it might explain ours. :P

**Comment by rbtcollins** [comment]
@miki725 if you can't reproduce it thats fine - can you at least verify against Python 3.5 to see if its a backport specific issue or not?

**Comment by miki725** [comment]
sure. Ill try to do that this weekend. my work computer does not have 3.5 installed already...

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
