### ISSUE TITLE
No Changelog in any recent releases

### ISSUE THREAD

**Issue by drawks** [testing-cabal/mock#285]
I only bothered to check the last 4 tagged releases, but I don't see anything except for a dead symbolic link from "docs/changelog.txt" to "../Changelog"

**Comment by drawks** [comment]
seems to be either related to or a dupe of #277

**Comment by rbtcollins** [comment]
hmm, 
python setup.y sdist
tar tzf dist/mock-1.1.4.dev3.tar.gz 
...
mock-1.1.4.dev3/ChangeLog

- so its being created. Looks like egg_info isn't sufficient to create it.

How have you been looking?

**Comment by rbtcollins** [comment]
@drawks I'll close this in a few days on the assumption you looked in git rather than an sdist. If not, please do reply.
