### ISSUE TITLE
mock_open().readlines() doesn't seem to work in 1.2.0

### ISSUE THREAD

**Issue by ralsina** [testing-cabal/mock#291]
I have a test that was working in 1.1.4 where this mock is created:

```
        file_metadata = ".. slug: write-tests-now\n"\
                        ".. date: 2012/09/15 19:52:05\n"\
                        ".. tags:\n"\
                        ".. link:\n"\
                        ".. description:\n"

        opener_mock = mock.mock_open(read_data=file_metadata)
        opener_mock.return_value.readlines.return_value = file_metadata

        with mock.patch('nikola.post.io.open', opener_mock, create=True):
            meta, nsm = get_meta(post, 'file_with_metadata')
```

The actual implementation of get_meta is uninteresting, here's what I see in pdb here:

```
-> meta_data = [x.strip() for x in meta_file.readlines()]
(Pdb) meta_file.readlines()
u'.. title: Nikola needs more tests!\n.. date: 2012/09/15 19:52:05\n.. tags:\n.. link:\n.. description:\n\nPost content\n'
(Pdb) meta_file.seek(0)
<MagicMock name='open().seek()' id='140399406068560'>
(Pdb) meta_file.read()
'.. title: Nikola needs more tests!\n.. date: 2012/09/15 19:52:05\n.. tags:\n.. link:\n.. description:\n\nPost content\n'
```

So ... it seems readlines() does the same thing as read() and doesn't split in lines?

**Comment by rbtcollins** [comment]
mock_open has the same code as 1.1.0 through 1.1.3, but not 1.1.4 (where we rolled a regression back from 1.1.4 in 1.2.0)

Perhaps you could test this against Python 3.5 alpha4 ?

**Comment by ralsina** [comment]
Sorry, don't have a lot of time to try building alpha versions of python to test this :-(

I had this code working  on 1.1.3 using a list as file_metadata, then when 1.1.4 came out I changed it to a string because that seemed to me what the documentation said ... is it meant to be a list? In that case I can revert the "fix" I did for 1.1.4 and this would go away.

**Comment by rbtcollins** [comment]
Yes, please revert your fix for 1.1.4: I think we will be re-introducing
that change, but only once the other issues with the patch are addressed.

I'm sorry for the flux you're experiencing here :(

**Comment by ralsina** [comment]
Ok, I'll do it. And no problem, things happen :-)

**Comment by rbtcollins** [comment]
Oh, one more thing:

      opener_mock = mock.mock_open(read_data=file_metadata)
      opener_mock.return_value.readlines.return_value = file_metadata

^ thats kindof weird. read_data sets up a readlines() call for you. So I the thing you encountered where readlines() wasn't splitting is that you've overridden the return value of readlines yourself. Use either read_data, or .readlines.return_value = .., but not both :)

**Comment by ralsina** [comment]
Ahhhh old code! Indeed that bug is my own, thanks!

**Comment by rbtcollins** [comment]
I'm going to close this, I think we've resolved both things.
