### ISSUE TITLE
Python version restriction in setup script

### ISSUE THREAD

**Issue by iamit** [testing-cabal/mock#293]
While installing the mock versions 1.1.x (I tried 1.1.0, 1.1.1, 1.1.2, 1.1.3 ) I get this error:

error: Setup script exited with error in setup command: Invalid environment marker: (python_version<"3.3" and python_version>="3")
An error occured when trying to install mock 1.1.0. Look above this message for any errors that were output by easy_install.

**Comment by rbtcollins** [comment]
Fixed in 1.2.0 (will error about needing setuptools 17.1)
