### ISSUE TITLE
Re-add version sections to changelog

### ISSUE THREAD

**Issue by jezdez** [testing-cabal/mock#299]
18c9bbd7e67055041260ae905891dee74586409c seems to have completely removed the old changelog and I think the new `NEWS` file would be easier to understand with the former structure of having per-version changes listed. This is feedback following my tweet https://twitter.com/jezdez/status/625761569666940928

**Comment by jezdez** [comment]
Ah, a minor issue, but related, there is a stale symlink in `docs/changelog.txt`

**Comment by rbtcollins** [comment]
The changelog generated into the sdist is split:

```
CHANGES
=======

1.3.0
-----

* Update sync point
* Issue #21750: Further fixup to be styled like other mock APIs
* Typo fix in mock.patch

1.2.0
-----

* Revert "Issue #21750: mock_open.read_data can now be read from each instance, as it"
```

etc, and the symlink in docs/changelog.txt points to that changelog for doc builds. When we get rtd docs building again (pending on a pbr 1.4 release, next week I hope), there will be a built version online for easy access.

**Comment by jezdez** [comment]
Aha, that's really unfortunate as I'm usually looking in the version control managed source to find information like this and not the source distribution. To clarify, is pbr actually *generating* that file from Git history, or how does this magic work?

**Comment by rbtcollins** [comment]
Yes, from git history.

**Comment by rbtcollins** [comment]
https://mock.readthedocs.org/en/latest/changelog.html <- generated changelog.
