### ISSUE TITLE
setup/teardown support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#30]
```
It would be great if there was a support for using mock in two steps, like this;
{{{
class TestSth(TestCase):
    def setUp(self):
        self._original_state = mock.setup_mocking("sys.stdin")
    def tearDown(self):
        mock.teardown_mocking(self._original_state)
}}}
```

Original issue reported on code.google.com by `kon...@gmail.com` on 10 Jun 2010 at 9:49

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
