### ISSUE TITLE
create_autospec doesn't work with chained attribute setting

### ISSUE THREAD

**Issue by AdrianTeng** [testing-cabal/mock#307]
It is well known that you can pass keyword arguments to `create_autospec` to set attributes:

```
class Spam(object):
    def foo(self):
        return 42

self = create_autospec(Foo, bar=42) 

>>> self.bar
42
```

It is also known that `Mock` supports mocking multiple chained attribute setting / calls `return_value` setting:

```
my_mock = Mock(**{'foo.bar.return_value': 42})

>>> my_mock.foo.bar()
42
```

Unfortunately chained attribute setting doesn't work for `create_autospec` with kwargs:

```
self = create_autospec(Foo, **{'baz.return_value': 42, 'qax.return_value': 0})
```

This line yield `AttributeError: Mock object has no attribute 'baz'` instead.

**Comment by rbtcollins** [comment]
Please file this as a bug in the CPython bug tracker, where mock development takes place. This tracker is for the mechanics of the rolling backport only. Thanks!

https://bugs.python.org/
