### ISSUE TITLE
 Failed to mock the python urlopen function

### ISSUE THREAD

**Issue by sih4sing5hong5** [testing-cabal/mock#313]
I cannot mock the `urlopen` directly. But `urllib2.urlopen` or `urllib.request.urlopen)` worked. I don't know why.
I tested both python 2 and 3.

### mock in python 2.7.10 
```
from mock import patch
from urllib2 import urlopen
import urllib2

@patch('urllib2.urlopen')
def openPatch(urlopenMock):
    print(urlopenMock)
    print(urlopen)
    print(urllib2.urlopen)

openPatch()
```
The result:
```
<MagicMock name='urlopen' id='140086303159184'>
<function urlopen at 0x7f6861aac5f0>
<MagicMock name='urlopen' id='140086303159184'>
```

### mock in python 3.4
```
from mock import patch
import urllib
from urllib import request
from urllib.request import urlopen

@patch('urllib.request.urlopen')
def openPatch(urlopenMock):
    print(urlopenMock)
    print(urlopen)
    print(request.urlopen)
    print(urllib.request.urlopen)

openPatch()
```
The result:
```
<MagicMock name='urlopen' id='140002395279200'>
<function urlopen at 0x7f54d909eae8>
<MagicMock name='urlopen' id='140002395279200'>
<MagicMock name='urlopen' id='140002395279200'>
```
It also failed with `unittest.mock` with python 3.4

**Comment by rbtcollins** [comment]
You mocked by name, but used a prior reference.

The urlopen in your sample code is not the one that mock.patch patches - it patches the one in the module itself. This is the difference between binding (mapping a /name/ to a value) and mutating values. mock.patch rebinds names. mock.patch('__main__.urlopen') would do what you expect, I think.

**Comment by sih4sing5hong5** [comment]
I traced the `python3.4/urllib/request.py`.
```python
__all__ = [
    # Functions
    'urlopen', ...
    ]
...
def urlopen(url, ...):
    ...
```
Do you mean I patch the `__all__` real function, but I use the `def urlopen()` one?

**Comment by chenzeng765** [comment]
hi, I have got a same question. do you fix it? @sih4sing5hong5

**Comment by sih4sing5hong5** [comment]
import the upper package level instead in being tested code.
You should import the at least 2 upper package levels of the object which be mocked.
If you want to mock `urllib.request.urlopen`
You should write them like
```
from urllib import request
request.urlopen(...)
```
