### ISSUE TITLE
patch.dict spoils order of items in collections.OrderedDict

### ISSUE THREAD

**Issue by oblalex** [testing-cabal/mock#315]
Hi!

Current implementation of `patch.dict` spoils order of items in `collections.OrderedDict`, because [it explicitly converts passed `values` to `dict`](https://github.com/testing-cabal/mock/blob/1.3.0/mock/mock.py#L1708):

```python

# support any argument supported by dict(...) constructor
self.values = dict(values)
```

Most obvious way is to check if `values` is an instance of `dict`. If it's not, then we need to convert it to dict:

```python

if not isinstance(values, dict):
    values = dict(values)

self.values = values
```

This will work for `OrderedDict`, because it's a subclass of `dict`. But this will not work for `UserDict.UserDict`, `UserDict.DictMixin`, `collections.MutableMapping`, etc., because they do not subclass `dict`. So, better way is to less strict check and look if `values` implements `dict`-like interface, e.g.:

```python

if not hasattr(values, 'update'):
    values = dict(values)

self.values = values
```

Here is a question existence of what attrs to check.

Any ideas?

Thanks!

**Comment by rbtcollins** [comment]
Please open this ticket on https://bugs.python.org - all mock development takes place there. We just do the backporting here.
