### ISSUE TITLE
_mock_call does not properly grab args and kwargs

### ISSUE THREAD

**Issue by paetling** [testing-cabal/mock#318]
Consider the following lines of code:
```
def test_mock(val):
    fake_mock = Mock()
    a = {}  
    fake_mock.func(a)
    a['val'] = 5
    fake_mock.func.assert_has_calls([call({})])
```

What i would expect would be for this statement to pass.  What I actually see is the following:

```
Traceback (most recent call last):
File "/gc/gclib/python/tests/kafka_production/encoding_test.py", line 121, in test_mock
fake_mock.func.assert_has_calls([call({})])
File "/usr/local/lib/python2.7/dist-packages/mock.py", line 863, in assert_has_calls
'Actual: %r' % (calls, self.mock_calls)
AssertionError: Calls not found.
Expected: [call({})]
Actual: [call({'val': 5})]
```

Mock thinks that I have passed in `{'val': 5}`, when I in fact did pass in `{}`.  The errors seems to be the way args and kwargs are being grabbed in `_mock_call` function

**Comment by paetling** [comment]
I am going to try and create a failing test and submit a pr.

**Comment by rbtcollins** [comment]
Please do so in the cpython bug tracker: bugs.python.org (mock is just a rolling backport).
