### ISSUE TITLE
assert_called_with doesn't work properly in some cases

### ISSUE THREAD

**Issue by rbranche** [testing-cabal/mock#319]
assert_called_with doesn't work properly in some cases when list/dict is passed to function and then modified later in the function.

    changes = []
    process_messages(messages, changes)
    changes.append("new_changes")

 ---

    with patch('project.process_messages') as process_messages_mock:
        process_all_messages()
        process_messages_mock.assert_called_with(["message1"], [])

---
    AssertionError: Expected call: process_messages(["message1"], [])
    Actual call: process_messages(["message1"], ["new_change"])

---

mock should do a deep copy of the args/kwargs to the _Call class to properly snapshot the actual called-with parameters:

    --- .../mock/mock2.py	2015-09-04 17:04:40.000000000 -0700
    +++ .../mock/mock.py	2015-09-04 17:03:53.000000000 -0700
    @@ -54,6 +54,7 @@
     )
     
     
    +import copy
     from functools import partial
     import inspect
     import pprint
    @@ -2122,9 +2124,9 @@
                     kwargs = value
     
             if two:
    -            return tuple.__new__(cls, (args, kwargs))
    +            return tuple.__new__(cls, copy.deepcopy((args, kwargs)))
     
    -        return tuple.__new__(cls, (name, args, kwargs))
    +        return tuple.__new__(cls, copy.deepcopy((name, args, kwargs)))
     
     
         def __init__(self, value=(), name=None, parent=None, two=False,

**Comment by rbtcollins** [comment]
Bugs with mock itself (vs the backporting process) should be filed in https://bugs.python.org/

Thanks!
