### ISSUE TITLE
ImportError: cannot import name wraps

### ISSUE THREAD

**Issue by Cueroqu** [testing-cabal/mock#321]
➜  server git: ✗ sudo pip install mock
Collecting mock
  Downloading mock-1.3.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 165kB/s
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /Library/Python/2.7/site-packages (from mock)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /Library/Python/2.7/site-packages (from mock)
Collecting six>=1.7 (from mock)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six, mock
Successfully installed mock-1.3.0 six-1.9.0

Traceback (most recent call last):
  File "test_test.py", line 3, in <module>
    import mock
  File "/Library/Python/2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/Library/Python/2.7/site-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps

**Comment by rbtcollins** [comment]
I suspect your sys.path has six on it before the one installed by pip. This should let you see:
```
import six
print(six.__file__)
```

**Comment by Cueroqu** [comment]
Oh, yes. Thank you!

**Comment by rbtcollins** [comment]
out of interest, what path was six installed at?

**Comment by Cueroqu** [comment]
Originally, it was in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ and I removed it now.

**Comment by RussellBradley** [comment]
was encountering same issue as @Cueroqu, removing six from sys.path worked for me too. Thanks @rbtcollins!
