### ISSUE TITLE
mock.assert_called_once() silently fails

### ISSUE THREAD

**Issue by ajslater** [testing-cabal/mock#322]
mock.assert_called_once() as of sometime between mock 1.0.1 and 1.3.0 assert_called_once() still exists and silently fails.

It has been replaced by assertTrue(mocked_function.called), but there's no way to know that.

Removing the method entirely, or even better, adding a deprecation warning would be very nice.

**Comment by rbtcollins** [comment]
Hi, assert_called_once is tested, so I'm fairly sure its not broken for everyone. Could you perhaps include a reproduction example of the situation you are encountering?

**Comment by mgedmin** [comment]
Huh?  [There's no `assert_called_once`](https://github.com/testing-cabal/mock/search?utf8=%E2%9C%93&q=assert_called_once).  There's an `assert_called_once_with()`.

**Comment by ajslater** [comment]
There was. It has since been removed.
Today I cannot replicate. I now suspect my bug report was caused by a stale old .pyc or something after upgrade.

**Comment by rbtcollins** [comment]
Sorry, I missed the typo.

There was *never* assert_called_once - it was merely that mock didn't error when folk used that name.

http://bugs.python.org/issue24651 is a related bug about the design space here.
