### ISSUE TITLE
Python 2, Unicode, Repr make Mock fail

### ISSUE THREAD

**Issue by ewjoachim** [testing-cabal/mock#328]
Hi,

I get a UnicodeDecode error in mock v1.3.0 for python 2 if I do the following (which I believe is completely normal and should not lead to a bug).
(Analysis of why the bug happens is below). Reproduction code is [here] (http://mybinder.org/repo/ewjoachim/binders/Mock.ipynb) (feel free to play with it, and long live Binders).

 1. Create a Mock object ``f``.
 2. Call it using a kwargs dict whose key is unicode and whose value's ``__repr__`` contains any non-ascii character (``f(**{u"a": obj})`` where ``repr(obj) == "é"``)
3. call ``f.mock_calls.__repr__``

This will fail due to the following :
``_format_call_signature`` contains the following code:
```python
    kwargs_string = ', '.join([
        '%s=%r' % (key, value) for key, value in sorted(kwargs.items())
    ])
```

The form ``"%r" % obj`` in python 2 __ONLY__ works for obj returning at least one non ascii character if both the interpolating string and the repr are python2 ``str`` (a.k.a bytes) objects.

In our case, the ``key`` object is Unicode, because it is the object that was passed to the kwargs dict. Python 2 reacts to that by using unicode for all the interpolation and converting everything back to a string in the end. Needless to says that without proper string encoding information, the conversion is bound to fail.

As a final note, it's really common to have unicode keys for dicts in Python 2 if you use ``from __future__ import unicode literals`` and I'm convinced (maybe I 'm wrong ?) I'm not doing something I shouldn't do.

A possible fix :
```python
if isinstance(key, unicode):
    key = key.encode("utf8")
```

**Comment by rbtcollins** [comment]
Hi, yes this is a bug. If you could put a test case for it together, we can see about getting your fix into a release.

**Comment by ewjoachim** [comment]
Done ! :)

**Comment by ewjoachim** [comment]
Done again, with proper history !
