### ISSUE TITLE
MagickMock __str__ sometimes returns MagickMock instead of str

### ISSUE THREAD

**Issue by skonieczny** [testing-cabal/mock#336]
This bug results in raising `TypeError: __str__ returned non-string (type MagicMock)`
Following program can reproduce it:
```
from threading import Thread
from mock.mock import MagicMock


def main():
    mocks = [MagicMock() for _ in range(1000)]

    def in_thread():
        for m in mocks:
            str(m)

    threads = [Thread(target=in_thread) for _ in range(10)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()


if __name__ == '__main__':
    main()
```
For me it rasies few times: 
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "../misc/magic_mock_str_bug.py", line 11, in in_thread
    str(m)
TypeError: __str__ returned non-string (type MagicMock)
``` 
I have run it with mock v. 1.3.0 and both python 2.7 and 3.5.

**Comment by rbtcollins** [comment]
That code is not threadsafe - Mock itself has no locking, so if you're using mocks across threads you need to supply appropriate locking yourself (just as you would have to for a non-threadsafe __str__ implementation in your code. I'm not sure there is anything sensible we *can* do - but having a highly locked variant of mock might be useful to some folk: if so, its definitely something to build upstream in CPython, where mock is developed (vs backported like it is here). https://bugs.python.org to file a bug on this upstream.
