### ISSUE TITLE
six dependency needs to be versioned

### ISSUE THREAD

**Issue by wichert** [testing-cabal/mock#337]
mock depends on six.wraps, which does not exist in all six versions. This was causing some of our builds to fail when they picked up an OS-provided six package:

```
  File "/srv/src/local/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/srv/src/local/lib/python2.7/site-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps
ERROR: could not load /srv/src/tests/conftest.py
```

**Comment by dcbaker** [comment]
+1 I've run into this problem as well, when I needed to extend support back to six 1.5.2 for my project I ran into basically the same error.

**Comment by rbtcollins** [comment]
The six dependency is versioned - 1.7 in 1.3.0, and 1.9 in the upcoming release. Likely you've hit  pypa/pip#998 .

**Comment by benf-wspdigital** [comment]
The referenced issue (“Fix #982 by using the effective user id on unix systems instead of depen...”) does not have any obvious connection to this behaviour.

Certainly there is no information at that issue to help with resolving this one.

**Comment by benf-wspdigital** [comment]
This issue remains a problem in ‘mock’ version 2.0.0:

`
  File …
    import mock
  File "/Users/benfinney/.virtualenvs/BOC/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/Users/benfinney/.virtualenvs/BOC/lib/python2.7/site-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps
`

**Comment by cjw296** [comment]
Closing for now, we can re-open if it's re-reported.
