### ISSUE TITLE
There is no changelog any more

### ISSUE THREAD

**Issue by do3cc** [testing-cabal/mock#339]
docs/changelog.txt is a symbolic link to ../Changelog
Changelog does not exist

**Comment by svetlyak40wt** [comment]
Seems that commit 18c9bbd7e670 removed it.

**Comment by rbtcollins** [comment]
Changelog is created by the build system just-in-time.  See e.g. http://mock.readthedocs.org/en/latest/changelog.html for built output.

**Comment by svetlyak40wt** [comment]
Cool. I was investigating why [mock's release notes](https://allmychanges.com/p/python/mock/) at AllMyChanges.com does not update correctly. Now I see, it used wrong datasource http://www.voidspace.org.uk/python/mock/changelog.html. Thank you, Robert.

BTW, please, tell me, which script you are use to build changelog automatically?

**Comment by svetlyak40wt** [comment]
@rbtcollins which tool do you use to generate changelog?

May be remove a symlink `docs/changelog.txt` from git repository to not confuse developers?

**Comment by rbtcollins** [comment]
The symlink is there so the generated changelog is included in docs builds.

python setup.py build_sphinx should generate it for you. - e.g. 

```
pyt(scratch)robertc@lifelesstab:~/work/mock$ python setup.py build_sphinx
running build_sphinx
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.1s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.1s)
Running Sphinx v1.2.3
loading pickled environment... done
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] changelog

/home/robertc/work/mock/docs/changelog.txt:519: WARNING: Inline strong start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] changelog
writing output... [100%] index

writing additional files... genindex search
copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 1 warning.
Running Sphinx v1.2.3
loading pickled environment... done
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... mock.1 { changelog }
build succeeded.
```

**Comment by do3cc** [comment]
Unfortunately, there is no link to the changelog now in the repo itself, nor on the pypi page.

**Comment by do3cc** [comment]
Oh, and neither does the pypi page point to mock.readthedocs.org, nor the REAME.

**Comment by do3cc** [comment]
Does it make sense if the readme table with the important links contains two homepage links? One for the included mock starting with Python 3.3(?) The other homepage link for the backported version?

**Comment by svetlyak40wt** [comment]
@rbtcollins I can't build docs. Here the error:

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/private/tmp/mock/pbr-1.8.1-py2.7.egg/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/private/tmp/mock/pbr-1.8.1-py2.7.egg/pbr/util.py", line 261, in cfg_to_args
    wrap_commands(kwargs)
  File "/private/tmp/mock/pbr-1.8.1-py2.7.egg/pbr/util.py", line 541, in wrap_commands
    for cmd, _ in dist.get_command_list():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 772, in get_command_list
    klass = self.get_command_class(cmd)
  File "/private/tmp/mock/env/lib/python2.7/site-packages/setuptools/dist.py", line 385, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/private/tmp/mock/env/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
ImportError: No module named upload
error in setup command: Error parsing /private/tmp/mock/setup.cfg: ImportError: No module named upload
```

And here what I've got in my working virtualenv:

```
(env)[art@213:/tmp/mock]% pip freeze
funcsigs==0.4
six==1.10.0
```

**Comment by rbtcollins** [comment]
I believe that was a bug in a setuptools release and if you update your setuptools it should work.

**Comment by houglum** [comment]
Would it be feasible to provide a placeholder for the Changelog file (which should just get overwritten upon build, correct?), rather than having a broken link?

I'd like to use mock as a submodule in gsutil, but the broken link is causing issues in some existing code. Specifically, a call to shutil.copytree will fail when it encounters broken links such as this.

**Comment by rbtcollins** [comment]
Copytree follows links? Ugh. Uhm a placeholder in the git tree? I'd be ok with that - care to put a patch together (and test that it overwrites correct in new clones and things like that?)

**Comment by houglum** [comment]
Sure, submitted PR #362
