### ISSUE TITLE
PR idea: Add an assert_called() method

### ISSUE THREAD

**Issue by amitsaha** [testing-cabal/mock#341]
Would a PR for adding a `assert_called()` method be welcome for inclusion? We do have a `assert_not_called()` method, so I think this may be a good idea. Please let me know and I will work on it.

**Comment by rbtcollins** [comment]
We ask that all enhancements be done on the Python bug tracker - this trails (closely) Python since it got merged in, rather than leading. https://bugs.python.org/. Thanks!

**Comment by amitsaha** [comment]
Thanks, done: http://bugs.python.org/issue26323

**Comment by amitsaha** [comment]
The stdlib now has two new methods (https://docs.python.org/3.6/whatsnew/3.6.html#unittest-mock) , what is the usual process of backporting?
