### ISSUE TITLE
Backport assert_called() and assert_called_once() methods

### ISSUE THREAD

**Issue by amitsaha** [testing-cabal/mock#342]
The stdlib now has these two new methods (https://docs.python.org/3.6/whatsnew/3.6.html#unittest-mock). Would be happy to back port these, should I submit a PR?

**Comment by rbtcollins** [comment]
See under backporting in the docs.

**Comment by amitsaha** [comment]
Could you please point me to the docs you are referring to?

**Comment by rbtcollins** [comment]
http://mock.readthedocs.org/en/latest/#maintainer-notes or https://github.com/testing-cabal/mock/blob/master/docs/index.txt#L147

**Comment by rbtcollins** [comment]
That said, I've the time to do a backporting run this afternoon, so you can leave it with me.

**Comment by amitsaha** [comment]
Cool, thank you.

**Comment by berkerpeksag** [comment]
Should we wait for Python 3.6 release first?

**Comment by rbtcollins** [comment]
@berkerpeksag I don't think so: there's nothing incompatible in the stdlib changes - things that broke won't break, and new test methods. Anyhow, backported into git.

**Comment by amitsaha** [comment]
Thanks @rbtcollins !
