### ISSUE TITLE
Documentation wasn't updated to version 2.0.0

### ISSUE THREAD

**Issue by svetlyak40wt** [testing-cabal/mock#348]
I noticed, that version 2.0.0 was uploaded to the PyPi, but documentation http://mock.readthedocs.org/en/latest/changelog.html says it is built for 1.4.0.dev19.

Please, update documentation.

**Comment by rbtcollins** [comment]
http://mock.readthedocs.org/en/stable/ has the 2.0.0 docs; I'm not sure why the 'latest' docs build hasn't picked up the commits to master. I'll try and tickle it.

**Comment by rbtcollins** [comment]
did a manual build of latest, all good now.
