### ISSUE TITLE
Pbr setup dependency causing headaches in closed environments

### ISSUE THREAD

**Issue by simonpercivall** [testing-cabal/mock#349]
Having an extremely early dependency on `pbr` requires `pbr` to be installed before `pip` (for instance) can do anything useful with the `mock` package. This complicates installation in closed environments, since the `pbr` package needs to be installed separately before `mock` is installed.

**Comment by rbtcollins** [comment]
So the underlying issue here is that pip doesn't process setup_requires. Thats not a mock issue per se, though I do understand how it impacts you. My advice: install the wheel we publish, rather than from .tar.gz, and then the runtime dep is handled just fine by pip with no special concerns.
