### ISSUE TITLE
Mock(2.0.0).assert_has_calls() raise AssertionError in two same calls

### ISSUE THREAD

**Issue by jekin000** [testing-cabal/mock#353]
hello, i use Mock (2.0.0) in python2.7,and found this issue.

Example:
test.py

```
from mock import Mock,call
class BB(object):
    def __init__(self):pass
    def print_b(self):pass
    def print_bb(self,tsk_id):pass

bMock = Mock(return_value=Mock(spec=BB))
bMock().print_bb(20)
bMock().assert_has_calls([call.print_bb(20)])
```

python test.py
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    bMock().assert_has_calls([call.print_bb(20)])
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 969, in assert_has_calls
    ), cause)
  File "/usr/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Calls not found.
Expected: [call.print_bb(20)]
Actual: [call.print_bb(20)]
# 

print expected in mock.py assert_has_calls()
[TypeError('too many positional arguments',)]
# 

issue in cpython: http://bugs.python.org/issue26752

**Comment by svisser** [comment]
You're creating a new instance which doesn't have `print_bb(20)` calls. The following does work:

```python
from mock import Mock,call
class BB(object):
    def __init__(self):pass
    def print_b(self):pass
    def print_bb(self,tsk_id):pass

bMock = Mock(return_value=Mock(spec=BB))
bMock.print_bb(20)
bMock.assert_has_calls([call.print_bb(20)])
```

**Comment by lanzz** [comment]
Here is another example that triggers this issue:

```python
import mock
import unittest


class Foo(object):

    def __init__(self, a):
        pass

    def bar(self, a, b):
        return (b, a)


class FooTestCase(unittest.TestCase):

    def test_foo(self):
        mock_class = mock.Mock(spec_set=Foo)
        foo = mock_class(1)
        foo.bar(2, 3)
        mock_class.assert_has_calls(
            [
                mock.call(1),
                mock.call().bar(2, 3),
            ]
        )
```

Test run output:
```
$ ./bin/python -m unittest test
F
======================================================================
FAIL: test_foo (test.FooTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 23, in test_foo
    mock.call().bar(2, 3),
  File ".../lib/python2.7/site-packages/mock/mock.py", line 969, in assert_has_calls
    ), cause)
  File ".../lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Calls not found.
Expected: [call(1), call().bar(2, 3)]
Actual: [call(1), call().bar(2, 3)]

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
```

What I've found is that `Mock._call_matcher` attempts to bind the `bar(2, 3)` call to `mock_class._spec_signature`, but that's the signature of the `Foo` class (`Foo.__init__(self, a)`, single positional argument), not that of the `Foo.bar` method (`Foo.bar(self, a, b)`, two positional arguments), thus it returns `TypeError('too many positional arguments')` instead.

**Comment by guboi72** [comment]
Instead of assert_has_calls, it is possible to do self.assertEqual(self.mock_class.method_calls, [call_1, call_2, call_3]).

**Comment by rbtcollins** [comment]
Does this trigger in Python 3.6 using unittest.mock, or is it a backport-only artifact?

**Comment by feluelle** [comment]
> Does this trigger in Python 3.6 using unittest.mock [...]

Yes it just did for me.

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.

**Comment by lanzz** [comment]
I love it how it took _two years and a half_ to close this bug report with "report it upstream instead" 🙄

**Comment by cjw296** [comment]
Joys of open source, we work on stuff when we have the time and energy :-)
