### ISSUE TITLE
Mock autospec does not work with subclasses of property()

### ISSUE THREAD

**Issue by amauryfa** [testing-cabal/mock#356]
When patching a class, `mock.create_autospec()` correctly detects properties and `__slot__` attributes, but not subclasses of `property` or other kinds of data descriptors.

I already filed upstream http://bugs.python.org/issue26750 with a patch, I don't know what is the best place to discuss this issue.

**Comment by berkerpeksag** [comment]
bugs.python.org is the right place discuss issues with mock (this tracker is mainly for backporting and 2.7 issues). I left some review comments at http://bugs.python.org/review/26750/
