### ISSUE TITLE
Why is it 2.0.0?

### ISSUE THREAD

**Issue by jakirkham** [testing-cabal/mock#358]
I'm trying to understand why mock is 2.0.0 and not still 1.x. What versioning scheme is used here (semantic?)? Are there some sort of compatibility breaks? What features (if any) are not included in Python 3.x? Is this only because of dropped support of some Python versions I have looked at the Changelog, but it isn't obvious to me what counts as API breaking changes here.

**Comment by rbtcollins** [comment]
We dropped support for 3.2, thats an API break, since if you are using 3.2 and installed an updated mock, it would not work.

**Comment by jakirkham** [comment]
Ok, that's fine. So, that is the only API break then or are there others?

Is there anything here that is not in Python 3.4 or 3.5 at present?

**Comment by rbtcollins** [comment]
You'd need to check the issue numbers from the commits / the changelog doc and cross reference them with the Python 3.5 branch changelog (or just see the referenced changesets on the issues themselves).

And yes, there's tonnes not in 3.4 from memory.

**Comment by jakirkham** [comment]
Sure, that's fine. I figured I would ask in case there was some mechanism here for tracking what is in Python 3.5.

Just to confirm, the only API break was dropping Python 3.2 support. Correct?
