### ISSUE TITLE
Unittesting with mock objects fails in tox with @patch decorator

### ISSUE THREAD

**Issue by arthurlogilab** [testing-cabal/mock#359]
I have some unittests that work fine when directly run with python (python -R -m coverage run -m pytest <FOLDER>/test), 

The code looks like this 

```
    @patch('elasticsearch.client.Elasticsearch.index')
    def test_es_hooks_modify(self, index):
```

and generates the following error when run in tox

```
/usr/lib/python2.7/dist-packages/mock/mock.py:721: AttributeError
___________________________________________________________ ExportElasticSearchTC.test_es_hooks_modify _____________________________________________________

args = (<test_elastic_search.ExportElasticSearchTC testMethod=test_es_hooks_modify>, <MagicMock name='index' id='140487100643792'>), keywargs = {}
extra_args = [<MagicMock name='index' id='140487100643792'>], entered_patchers = [<mock.mock._patch object at 0x7fc5b6522bd0>]
exc_info = (<type 'exceptions.AttributeError'>, AttributeError('assert_called',), <traceback object at 0x7fc5b39af638>)
patching = <mock.mock._patch object at 0x7fc5b6522bd0>, arg = <MagicMock name='index' id='140487100643792'>

    @wraps(func)
    def patched(*args, **keywargs):
        extra_args = []
        entered_patchers = []

        exc_info = tuple()
        try:
            for patching in patched.patchings:
                arg = patching.__enter__()
                entered_patchers.append(patching)
                if patching.attribute_name is not None:
                    keywargs.update(arg)
                elif patching.new is DEFAULT:
                    extra_args.append(arg)

            args += tuple(extra_args)
>           return func(*args, **keywargs)


```

Reading the mock code, I try out adding unsafe

```
    @patch('elasticsearch.client.Elasticsearch.index', unsafe=True)
    def test_es_hooks_modify(self, index):
```

And this works in both tox and directly from python. 

Is this a mock bug ? a pytest bug ? is tox doing something that might affect the way mock works ? (posted this on the tox bugtracker too https://bitbucket.org/hpk42/tox/issues/329/unittesting-with-mock-objects-fails-in-tox)

Do you need extra context ?

**Comment by svisser** [comment]
What does the code that you're trying to mock look like? It's possible that you're now mocking an `Elasticsearch` class but the `index` attribute is only available on the instance, not the class.

**Comment by cjw296** [comment]
I'm going to close this as it's been languishing for 2.5 years and it's unclear where the problem lies, please comment back if this is still a problem that you can provide a short reproducer for.
