### ISSUE TITLE
Problem with patch and new with kwargs

### ISSUE THREAD

**Issue by frank2411** [testing-cabal/mock#364]
Hi,

I've got a problem, or maybe there's a reason that I can't see, while specifying, in a patch decorator, a different new class and passing kwargs to it.

That's the class:

class PlaylistSolrMock(object):

```
def __init__(self, *args, **kwargs):
    print kwargs.get('valid_qs')

def models(self, *args):
    return self

def filter(self, django_id__in=[], *args, **kwargs):
    print django_id__in
```

This is how i use the decorator:

@mock.patch('videos.models.SearchQuerySet', new=PlaylistSolrMock, valid_qs=True)

In this case i get this error:
    - TypeError: Can't pass kwargs to a mock we aren't creating

In this other case ( if I inherit from the default mock class ) I get the same error.

class PlaylistSolrMock(mock.Mock):

```
def __init__(self, *args, **kwargs):
    print kwargs.get('valid_qs')
    super(PlaylistSolrMock, self).__init__()

def models(self, *args):
    return self

def filter(self, django_id__in=[], *args, **kwargs):
    print django_id__in
```

@mock.patch('videos.models.SearchQuerySet', new=PlaylistSolrMock, valid_qs=True)
#### I would like to know if there's something I'm doing wrong or, why, If I pass some kwargs to a custom object you raise this error.

P.S.

I'm only able to avoid this error specifying a new_callable and creating a custom init and call method.

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
