### ISSUE TITLE
patch decorator fails silently on generators

### ISSUE THREAD

**Issue by shoshber** [testing-cabal/mock#366]
(at least in my case)

I committed two tests before I realized the tests were not being run: https://github.com/nipy/nipype/blob/abe7920a051f1570ccce4b71f26f50102d6e4e12/nipype/testing/tests/test_utils.py#L23

I realized this afternoon, while writing some more tests, that tests with the patch decorator were all reported as "OK", even when I wanted them to fail. Turns out they aren't being run at all.

I commented out all the ``yield`` statements, and the tests ran just as they should.

I don't know exactly what is going on here, but might raising an error or warning be good here?

**Comment by rbtcollins** [comment]
Please file this on the Python bug tracker - this bugtracker only tracks the issues related to backporting mock to older Pythons.

That said, unittests can't be generators today, so whats happening is you have ```@patch``` around a generator, so when unittest runs the test, the generator is returned, and the framework immediately continues, letting your patch be unwound when gc / refcounting deallocates the generator. 

I'm closing this bug (as its in the wrong place).

**Comment by shoshber** [comment]
> unittests can't be generators today

I can't find anything online supporting this--can you explain what you mean point me somewhere? Thanks.

**Comment by shoshber** [comment]
We are using nose, which explicitly supports (or did support?) generators: http://nose.readthedocs.io/en/latest/writing_tests.html#test-generators

**Comment by rbtcollins** [comment]
patch returns a _patch object, whose __call__ does this:
```
    def __call__(self, func):
        if isinstance(func, ClassTypes):
            return self.decorate_class(func)
        return self.decorate_callable(func)
```

so after defining a test with @patch, you'll have the result of decorate_callable, which is a simple closure:

```
        @wraps(func)
        def patched(*args, **keywargs):
             ...
```

which isn't a generator. So this can be paraphrase as 'mock.patch of a generator returns a normal function'. That is a valid bug - please file it upstream as I requested.

**Comment by shoshber** [comment]
Ah, I see, you meant unittests with mock can't be generators today. Sorry for the misunderstanding. I filed the bug yesterday: https://bugs.python.org/issue27341

Thank you!

**Comment by rbtcollins** [comment]
No, I meant unittest - it does not support generators as tests. Nose is not unittest. Nose with mock.patch won't work today until that bug is addressed.
