### ISSUE TITLE
Module patching issue with test order on Python 2.7

### ISSUE THREAD

**Issue by lobsteropteryx** [testing-cabal/mock#367]
If a test with a patched module is run first, then both tests pass.  If a test that uses the real module is run first, then all the patched tests will fail.  For unittest, this comes down to the name of the test classes and/or functions.  I've verified that when the patched module is loaded first, the real module is still used in unpatched tests.

The real project is here:  https://github.com/gisinc/slap/blob/1-add-sha-to-git-parameter/tests/test_git.py

git.py
``` python
from subprocess import check_output

def get_changed_files():
    return check_output(['git',  'diff', '--name-only',  'HEAD~1']).splitlines()
```

test_git.py
```python
from unittest import TestCase
from mock import MagicMock, patch
from slap import git

# This always passes
class TestGitFileManager(TestCase):

    def test_get_args(self):
        git.get_changed_files = MagicMock(return_value=['foo.mxd', 'bar.txt', 'baz.MXD'])
        self.assertEqual(git.build_args(), '-i foo.mxd -i baz.MXD')


@patch('slap.git.check_output')
# This fails, but will pass if we rename to TestGitArguments, since this set of tests will run first
class TestGitZArguments(TestCase):

    def test_default_revision(self, mock_check_output):
        expected = ['git',  'diff', '--name-only',  'HEAD', 'HEAD~1']
        git.get_changed_files()
        mock_check_output.assert_called_once_with(expected)
```

**Comment by rbtcollins** [comment]
Your example is broken, as git.py is missing build_args(), and the first test is patching get_changed_files, not build_args.

To demonstrate, I added a trivial build_args and ran the tests, which gets 

With a trivial build_args added, and s/slap/git/g/ as I wrote to g.py locally, I get:
```
.F
======================================================================
FAIL: test_default_revision (t.TestGitZArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robertc/work/mock/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "t.py", line 20, in test_default_revision
    mock_check_output.assert_called_once_with(expected)
  File "/home/robertc/work/mock/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'check_output' to be called once. Called 0 times.

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
```

That is, the first test can run happily.

Now, test_default_revision fails in this order because you patched git.get_changed_files by hand, and didn't unwind it. Either:
```
with patch('git.get_changed_files', MagicMock....)):
    ....
```

or use an addCleanup to restore the original value,

or use @patch on the first test too.

**Comment by lobsteropteryx** [comment]
Error between keyboard and chair...sorry!

**Comment by rbtcollins** [comment]
No problems - its worth asking :).
