### ISSUE TITLE
Please write a prominent change log document, describing changes in each release

### ISSUE THREAD

**Issue by benf-wspdigital** [testing-cabal/mock#371]
The project has no change log document at the top level. (A GitHub home page also means there is no obvious place for a user to look for the change log.)

There is a `docs/changelog.txt` file, but it is empty. Regardless, the change log document should be at the top level IMO.

The document should describe all user-visible changes at each released version.

**Comment by rbtcollins** [comment]
Uhm http://mock.readthedocs.io/en/latest/changelog.html covers that I believe.

**Comment by benf-wspdigital** [comment]
The changelog should be part of the downloaded source. The existing `docs/changelog.txt` is an obvious place for it, or a top-level `CHANGELOG` document.
