### ISSUE TITLE
RTFD documentation still says 1.0.1, not 2.0

### ISSUE THREAD

**Issue by georgevreilly** [testing-cabal/mock#387]
At the top of the page at https://mock.readthedocs.io/en/latest/, it says `Mock 1.0.1 documentation`, then `Version: 1.0.1`, and later `The current version is 1.0.1`. It also says in the Changes section of the TOC, `2.0.0`, `1.3.0`, etc, so clearly the documentation has kinda, sorta been updated since 1.0.1.

**Comment by rbtcollins** [comment]
Indeed it does; probably in some metadata somewhere.

**Comment by annp89** [comment]
I clicked on 'build version' on Read the Docs and now the documentation for latest is correctly updated.
<img width="1362" alt="screen shot 2017-10-14 at 5 42 32 pm" src="https://user-images.githubusercontent.com/1740816/31580514-d79b4d26-b106-11e7-85ca-f34f60a5974f.png">

**Comment by cjw296** [comment]
Looks to no longer be an issue.
