### ISSUE TITLE
mock.patch.object return_value works unexpected result

### ISSUE THREAD

**Issue by khorolets** [testing-cabal/mock#388]
Hi! First of all thank for your work, it is great!

I am not sure is this an issue or a question, anyway, I would be glad to hear something from you.

I have a class with method `get_file` which is obviously getting a file. I need to mock it up, I'm doing:

```python
@mock.patch.object(seaweedfs, 'get_file')
def test_data_transformation_export_to_pfa_authorized(
        mock_get_file,
    ):
    mock_file_exists.return_value = '{"example": "json"}'
   ...
```

I've skipped details it is not important

Then I have some code, where I use that method.

```python
...
model = json.loads(seaweedfs.get_file(file_id))  # I am expecting '{"example": "json"}' as the result
...
```

But I'm getting the error:

```
TypeError: the JSON object must be str, not 'bool'
```

Debugger says that the result of `get_file` is `True`

Can you help me to understand is this a bug or I'm using it wrong?

Thank you!

**Comment by rbtcollins** [comment]
Your example as written has mock_get_file and then from nowhere mock_file_exists; I presume thats a typo, however if its not  it may provide a clue as to whats going on. I think you will need to reduce your test case until you've got one you can share the entirety of, for us to figure out whats going on.

**Comment by khorolets** [comment]
@rbtcollins Thank you for your answer! You are right it was a typo. In my original test, I was mocking both `file_extsts` and `get_file`.

What kind of information can I provide to help to figure out whats going on?

**Comment by khorolets** [comment]
Want to clarify. My problem is that I use `.return_value = 'some specific not boolean value'` but in the end, I don't get that `return_value` I've set, but boolean.

**Comment by khorolets** [comment]
Not sure what happened, maybe I've upgraded to a newly version, but it works as I expect now. Sorry for bothering and thanks for your help.
