### ISSUE TITLE
support for "mock.call(a=1) in mock.call(a=1, b=1)"

### ISSUE THREAD

**Issue by amarao** [testing-cabal/mock#390]
Hello.

I think this is very idiomatic:

    m=mock.MagicMock()
    m(a=1,b=2)
    mock.call(a=1) in m.call_args

Unfortunately now it returns 'False'. I think 'call_args' and 'call' should support proper `__contains__` method for such case.

Thanks.

**Comment by rbtcollins** [comment]
I'm not sure I agree, but nevertheless this is an upstream bug - it should be fixed in cpython first.

**Comment by amarao** [comment]
I'm not sure it has something to do with upstream. mock.call should just implement smart __contains__ function, aren't it?

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
