### ISSUE TITLE
Problems to use with 'nosetests'

### ISSUE THREAD

**Issue by guilhermereis-luizalabs** [testing-cabal/mock#391]
I had trouble running the tests with lib nose (http://nose.readthedocs.io/en/latest/). So I added the **appdirs** and **packaging** libs in requiremens.txt

https://github.com/guilhermereis-luizalabs/mock/blob/master/requirements.txt

What do you think about this? Did this happen to me?

**Comment by rbtcollins** [comment]
I'm a bit confused by this bug report; we don't use nosetests to develop mock; if you're using nosetests with some other package, then thats going to be an issue for your dependencies with that package, not with mock's dependencies.
