### ISSUE TITLE
Mock with spec object does not ensure method call signatures

### ISSUE THREAD

**Issue by bclau** [testing-cabal/mock#393]
Mock can accept a spec object / class as argument, making sure that accessing attributes that do not exist in the spec will cause an AttributeError to be raised, but there is no guarantee that the spec's methods signatures are respected in any way. This creates the possibility to have faulty code with passing unittests and assertions.

Steps to reproduce:

    >>> import mock
    >>> from mock.tests import testmock
    >>> m = mock.Mock(spec=testmock.Something)
    >>> m.meth()
    <Mock name='mock.meth()' id='140533095850448'>
    >>> m.meth.assert_called_once_with()
    >>> m.smeth()
    <Mock name='mock.smeth()' id='140533095942608'>
    >>> m.smeth.assert_called_once_with()

Expected behaviour: It should have raised a TypeError, since the method signature is: def meth(self, a, b, c, d=None):

Actual behaviour: No error.

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
