### ISSUE TITLE
mock.patch does not consume self / cls arguments

### ISSUE THREAD

**Issue by bclau** [testing-cabal/mock#396]
Currently, the autospec=True argument can be passed to mock.patch, but when trying to make assertions on the call and its arguments, it can fail, as it expects an instance / class instance reference as the first argument (self / cls arguments are not consumed when autospec-ing).

Steps to reproduce: 

    >>> import mock
    >>> from mock.tests import testmock
    >>>
    >>> with mock.patch.object(testmock.Something, 'meth', autospec=True):
    ...     smth = testmock.Something()
    ...     smth.meth(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
    ...     smth.meth.assert_called_once_with(mock.sentinel.a, mock.sentinel.b, mock.sentinel.c, mock.sentinel.d)
    ...
    <MagicMock name='meth()' id='139792133225424'>
    Traceback (most recent call last):
      File "<stdin>", line 4, in <module>
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 318, in assert_called_once_with
        return mock.assert_called_once_with(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 948, in assert_called_once_with
        return self.assert_called_with(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 937, in assert_called_with
        six.raise_from(AssertionError(_error_message(cause)), cause)
      File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
        raise value
    AssertionError: Expected call: meth(sentinel.a, sentinel.b, sentinel.c, sentinel.d)
    Actual call: meth(<mock.tests.testmock.Something object at 0x7f23e456dcd0>, sentinel.a, sentinel.b, sentinel.c, sentinel.d)

Expected result: no AssertionError.

**Comment by bclau** [comment]
Addressed by: https://github.com/testing-cabal/mock/pull/397

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.

**Comment by stephenfin** [comment]
For future reference, this has been [reported upstream](https://bugs.python.org/issue32092) (though unfortunately it does not appear to have progressed much further since :disappointed:)
