### ISSUE TITLE
autospecced mock on a function doesn't have assert_called_once/assert_not_called

### ISSUE THREAD

**Issue by 2uasimojo** [testing-cabal/mock#398]
When I mock a class with an autospec, it has the assert_called_once and assert_not_called methods.

But when I mock a function or a method, it doesn't.

Example:

<pre>
#!/usr/bin/python

import mock
import pbr

print('mock version ' + str(pbr.version.VersionInfo('mock')))

def inspect_mock(title, the_mock):
    print(title)
    for p in ('assert_not_called', 'assert_called_once'):
        print("\t%s: %s" % (p, hasattr(the_mock, p)))
    print

def foo():
    pass

class Bar(object):
    def baz(self):
        pass

@mock.patch('__main__.foo', autospec=True)
def function_decorator(the_mock):
    inspect_mock("function decorated", the_mock)

@mock.patch('__main__.Bar', autospec=True)
def class_decorator(the_mock):
    inspect_mock("class decorated", the_mock)

@mock.patch('__main__.Bar.baz', autospec=True)
def method_decorator(the_mock):
    inspect_mock("method decorated", the_mock)

function_decorator()
class_decorator()
method_decorator()

inspect_mock("function inline mock.patch", mock.patch('__main__.foo', autospec=True).start())
m = mock.patch('__main__.Bar', autospec=True)
inspect_mock("class inline mock.patch", m.start())
m.stop()
m = mock.patch('__main__.Bar.baz', autospec=True)
inspect_mock("method inline mock.patch", m.start())
m.stop()

inspect_mock("function create_autospec", mock.create_autospec(foo))
inspect_mock("class create_autospec", mock.create_autospec(Bar))
inspect_mock("class method create_autospec", mock.create_autospec(Bar.baz))
inspect_mock("instance create_autospec", mock.create_autospec(Bar()))
inspect_mock("instance method create_autospec", mock.create_autospec(Bar().baz))
</pre>

Produces output;
<pre>
mock version 2.0.0
function decorated
        assert_not_called: False
        assert_called_once: False

class decorated
        assert_not_called: True
        assert_called_once: True

method decorated
        assert_not_called: False
        assert_called_once: False

function inline mock.patch
        assert_not_called: False
        assert_called_once: False

class inline mock.patch
        assert_not_called: True
        assert_called_once: True

method inline mock.patch
        assert_not_called: False
        assert_called_once: False

function create_autospec
        assert_not_called: False
        assert_called_once: False

class create_autospec
        assert_not_called: True
        assert_called_once: True

class method create_autospec
        assert_not_called: False
        assert_called_once: False

instance create_autospec
        assert_not_called: True
        assert_called_once: True

instance method create_autospec
        assert_not_called: False
        assert_called_once: False
</pre>

**Comment by JohnVillalovos** [comment]
We noticed the same thing today.

Also noticed when just printing the mocks see this:

    class mock with autospec=True
    <MagicMock name='Popen' spec='Popen' id='140597047651472'>

    function mock with autospec=True
    <function _ensure_console_pid_dir_exists at 0x7fdf4deff5f0>

**Comment by rbtcollins** [comment]
Could you please test with Python 3.6 unittest.mock - I'd like to see if this is a bug in the backports.

**Comment by 2uasimojo** [comment]
@rbtcollins With unittest.mock in py36, things started off better (those methods existed for all the mock.patch variants), but got a weird exception on create_autospec.  (Didn't spend any time debugging.)  Here's the output:

<pre>
function decorated
        assert_not_called: True
        assert_called_once: True

class decorated
        assert_not_called: True
        assert_called_once: True

method decorated
        assert_not_called: True
        assert_called_once: True

function inline mock.patch
        assert_not_called: True
        assert_called_once: True

class inline mock.patch
        assert_not_called: True
        assert_called_once: True

method inline mock.patch
        assert_not_called: True
        assert_called_once: True

Traceback (most recent call last):
  File "test.py", line 45, in <module>
    inspect_mock("function create_autospec", mock.create_autospec(foo))
  File "/usr/lib/python3.6/unittest/mock.py", line 2223, in create_autospec
    **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 1826, in __init__
    _safe_super(MagicMixin, self).__init__(*args, **kw)
  File "/usr/lib/python3.6/unittest/mock.py", line 924, in __init__
    _spec_state, _new_name, _new_parent, **kwargs
  File "/usr/lib/python3.6/unittest/mock.py", line 396, in __init__
    self._mock_add_spec(spec, spec_set, _spec_as_instance, _eat_self)
  File "/usr/lib/python3.6/unittest/mock.py", line 453, in _mock_add_spec
    _spec_as_instance, _eat_self)
  File "/usr/lib/python3.6/unittest/mock.py", line 89, in _get_signature_object
    return func, inspect.signature(sig_func)
  File "/usr/lib/python3.6/inspect.py", line 3002, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.6/inspect.py", line 2752, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/lib/python3.6/inspect.py", line 2227, in _signature_from_callable
    return _signature_from_function(sigcls, obj)
  File "/usr/lib/python3.6/inspect.py", line 2117, in _signature_from_function
    kind=_VAR_POSITIONAL))
  File "/usr/lib/python3.6/inspect.py", line 2418, in __init__
    raise TypeError("name must be a str, not a {!r}".format(name))
TypeError: name must be a str, not a <MagicMock name='foo.__code__.co_varnames.__getitem__()' id='140190987716928'>
</pre>

**Comment by 2uasimojo** [comment]
@rbtcollins Update: When I comment out the function create_autospec line (<tt>inspect_mock("function create_autospec", mock.create_autospec(foo))</tt>), the script completes, and all the variants print True.

**Comment by rbtcollins** [comment]
Ok, so this seems plausible to me that it should work, and as its broken in 3.6, its an upstream problem - please report to the python/cpython issue tracker.

**Comment by 2uasimojo** [comment]
Sure thing.  Uhhh, wherezat?

**Comment by lokal-profil** [comment]
https://bugs.python.org I believe per https://github.com/python/cpython/blob/master/README.rst

**Comment by 2uasimojo** [comment]
Thanks for that.  I'm kind of new to this kind of bug reporting, so please bear with me, but that guy looks like it's claiming to be fixed.  How would I go about getting the fix?  Do I have to patch it by hand?  And is there any way for me to realize the fix within py27?

**Comment by lokal-profil** [comment]
I'm not an expert but it looks like it didn't make it into 3.6.1 meaning it won't be available for at least another 2 months.

I don't know how/when backporting happens though.
