### ISSUE TITLE
Using autospec=True conflicts with 'wraps'

### ISSUE THREAD

**Issue by JohnVillalovos** [testing-cabal/mock#413]
If have autospec=True, then no ValueError is raised. If autospec=False or not defined, then the ValueError is raised.

```
import sys
from unittest import mock


def wrapped_func(value):
    raise ValueError(value)


@mock.patch('__main__.wrapped_func', autospec=True, wraps=wrapped_func)
def main(mock_wrap):

    wrapped_func("testing")


if '__main__' == __name__:
    sys.exit(main())
```

**Comment by Lukas0907** [comment]
I've commented your upstream bug report as well: https://bugs.python.org/issue31807#msg306273

**Comment by renaudl** [comment]
I need the same to twist result for certain input set and not other...

**Comment by cjw296** [comment]
Let's track upstream at https://bugs.python.org/issue31807
