### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Skeen** [testing-cabal/mock#414]
Hello,

According to the METADATA information on the package;

    cat site-packages/mock-2.0.0.dist-info/METADATA 

    Metadata-Version: 2.0
    Name: mock
    Version: 2.0.0
    ...
    License: UNKNOWN

Rather then UNKNOWN, perhaps it should say `Simplified BSD`.

**Comment by cjw296** [comment]
This is fixed on master.
