### ISSUE TITLE
mock.create_autospec fails if an attribute is a partial function

### ISSUE THREAD

**Issue by bclau** [testing-cabal/mock#418]
If an object's attribute is a partial function, mock.create_autospec will fail while trying to copy the partial functions' details to the mocked function, as the partial function does not have the __name__ attribute.

Example:

    import functools

    import mock

    class Proxy(object):
        def __init__(self, obj):
            self.obj

        def __getattr__(self, name):
            return functools.partial(self.__run_method, name)

        def __run_method(self, name, *args, **kwargs):
            return getattr(self.obj, name)(*args, **kwargs)

            
    a = mock.Mock()
    proxy = Proxy(a)

    mock.create_autospec(proxy)

Output:

      File "mock_functools.py", line 20, in <module>
        mock.create_autospec(proxy)
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 2324, in create_autospec
        _check_signature(spec, mock, is_type, instance)
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 210, in _check_signature
        _copy_func_details(func, checksig)
      File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 215, in _copy_func_details
        funcopy.__name__ = func.__name__
    AttributeError: 'functools.partial' object has no attribute '__name__'

This issue has been solved in Python 3 in the following commit: https://github.com/python/cpython/commit/161a4dd495dbf5cb12364e8f6e2d113cfd0633fc

**Comment by tirkarthi** [comment]
Just want to add to this there were no tests for this as part of the fixed commit and there was a similar report with https://bugs.python.org/issue32153. I have added a test case for this issue with the PR yet to merged with https://github.com/python/cpython/pull/10398.

**Comment by cjw296** [comment]
Okay https://github.com/python/cpython/pull/10398 is merged now, noting here so it also gets backported! Thanks for the fixes!

**Comment by cjw296** [comment]
This is landed in https://github.com/testing-cabal/mock/pull/451
