### ISSUE TITLE
Align error messages when mock call assertion fails

### ISSUE THREAD

**Issue by EdvardM** [testing-cabal/mock#424]
Rationale:

Mock objects print assertion failures in a way that is hard to read.

Example:

```
AssertionError: Expected call: <mock assertion failure: 1122331 ...>
Actual call: <mock assertion failure: 112331 ...>
```

After the patch:

```
AssertionError:
Expected call: <mock assertion failure: 1122331 ...>
Actual call:   <mock assertion failure: 112331 ...>
```

There's a quick implementation for this at 
https://github.com/EdvardM/mock/tree/better-actual-expected-error-messages

with tests. Though I'm still wondering should the calls be indentented, eg.

```
AssertionError:
  Expected call: <mock assertion failure: 1122331 ...>
  Actual call:   <mock assertion failure: 112331 ...>
```

**Comment by EdvardM** [comment]
Created PR #425

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
