### ISSUE TITLE
mock_open does not support seek

### ISSUE THREAD

**Issue by domanchi** [testing-cabal/mock#426]
**Example:**

```
$ cat foobar
some content here
$ cat example.py
import mock


def foobar():
    with open('foobar') as f:
        print(f.read())
        f.seek(0)
        print(f.read())


def mocked_foobar():
    m = mock.mock_open(read_data='blah')
    with mock.patch(
        'builtins.open',
        m,
    ):
        foobar()


if __name__ == '__main__':
    foobar()
    mocked_foobar()
$ python example.py
some content here

some content here

blah
```

From my initial investigations, it looks pretty hard to change, because it seems [only line-based file operations are supported](https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L2445).

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
