### ISSUE TITLE
mock.Mock() objects should have a default __name__

### ISSUE THREAD

**Issue by yatishb** [testing-cabal/mock#431]
```python
>>>> import mock
>>>> x = mock.Mock()
>>>> x.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...site-packages/mock/mock.py", line 700, in __getattr__
    raise AttributeError(name)
AttributeError: __name__
```

Mock objects are often used to mock functions and classes which have `__name__` attributes. Considering that I was thinking that it would be a good idea if the mocked objects behaved the same way and had this attribute natively.

**Comment by cjw296** [comment]
This repo is only for issues that are specific to the backport.
Please report issues with mock in the upstream bug tracker at https://bugs.python.org/.
Once issues are fixed upstream, they can be backported here.
