### ISSUE TITLE
backport remaining patches

### ISSUE THREAD

**Issue by cjw296** [testing-cabal/mock#442]
from @rbtcollins : Biggest outstanding thing is to fixup the back port automation now python is in git. It may be trivial in fact.

This lives in `/tools`

**Comment by pbasista** [comment]
Can someone explain what specifically needs to be done in order to resolve this issue?

**Comment by cjw296** [comment]
The backport tools provide a way to get patches from cpython and apply them to this code base.
It sounds like they broke when cpython moved to git on github. If someone can document how they work, and fix them to work with cpython on github, then we can use them to backport the necessary patches and get a release out.

**Comment by pbasista** [comment]
Do I understand correctly that the backporting is done manually?

If yes, then why not simply generate patch from the upstream git [repository](https://github.com/python/cpython/tree/master/Lib/unittest), e.g. by running:

```
$ git diff previous_patch_revision..v3.7.2 -- Lib/unittest/ > unittest.patch
```
And then use the existing script:

```
$ ./tools/applypatch-transform unittest.patch
```

I have tried it now and it seems to mostly work. I am not sure which version is the `previous_patch_revision`, so I have used `v3.7.0`. The result was a patch which applied mostly cleanly, except for a few hunks that need manual resolving.

**Comment by cjw296** [comment]
Hmm, looks like the tools rely on `filterdiff`, which doesn't appear to be present on macOS by default.

**Comment by cjw296** [comment]
I've started a branch to try and make some progress on this:
https://github.com/cjw296/mock/tree/fix_backporting

**Comment by cjw296** [comment]
Getting closer, now a PR:
https://github.com/testing-cabal/mock/pull/450

**Comment by cjw296** [comment]
Okay, merged, just 42 patches to backport :'(

**Comment by pbasista** [comment]
> just 42 patches to backport :'(

What specifically do you refer to as "patches"? The commits from upstream? If yes, is it important to preserve its commit history?

If not, then I think that it should be unnecessary to apply the commits individually. They can be combined into a single patch and applied at once. I believe that the result should be the same.

**Comment by tirkarthi** [comment]
> What specifically do you refer to as "patches"? The commits from upstream? If yes, is it important to preserve its commit history?

IMO it's good to have each commit from upstream land here instead of a single commit. If there is a regression in the backport not covered in tests then having separate commits would help in bisecting.

**Comment by cjw296** [comment]
Okay, we're all up to date.
