### ISSUE TITLE
drop pbr in favour of simple setup.py/setup.cfg

### ISSUE THREAD

**Issue by jakirkham** [testing-cabal/mock#446]
Appears there is a link committed at `docs/changelog.txt`. Should this be dropped or replaced with something. Would add this causes `pip install` to fail on Windows Python 2.7.

ref: https://ci.appveyor.com/project/conda-forge/mock-feedstock/builds/22603672/job/iy9k6vq2y17loj3h

**Comment by cjw296** [comment]
I have a feeling there's some automation that generates this file, it confused me when I first looked at it too... https://github.com/testing-cabal/mock/issues/442 may also be related.

**Comment by cjw296** [comment]
Yep, it's pbr, which seems to cause more confusion than it's automation saves.
I'm planning on removing it in favour of a simple setup.py/setup.cfg.

**Comment by cjw296** [comment]
pbr is now gone, if there are problems in conda once 3.0.0 is out, please let me know!

**Comment by jakirkham** [comment]
Thanks for your help @cjw296 !
