### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by pbasista** [testing-cabal/mock#447]
The latest release version [2.0.0](https://github.com/testing-cabal/mock/releases/tag/2.0.0) is almost 3 years old now. Can you please consider releasing a new version from the current master branch?

I would be particularly interested in a new release version which would contain the commit 07532a75003ec8e871e494f9f1ab8f28fa246f08 that adds the missing `assert_*` methods to the mocked object when autospec is used. With the current release version 2.0.0, errors similar to:
```
AttributeError: 'function' object has no attribute 'assert_not_called'
```
are reported when running Python 2. It seems to work fine with Python 3.

**Comment by cjw296** [comment]
This is blocked on:
https://github.com/testing-cabal/mock/issues/442
https://github.com/testing-cabal/mock/issues/446

I wonder if the specific issue you're referring to is related to:
https://github.com/testing-cabal/mock/issues/352
?

**Comment by pbasista** [comment]
> I wonder if the specific issue you're referring to is related to: #352

It does not seem to me that it is related, but I am not sure. The issue I was mentioning is fixed in master, so if #352 is fixed there as well, they may be related. In such case bisecting may show whether the commit which fixed it is also 07532a7.

**Comment by cjw296** [comment]
Note to self: when this happens, remember to update the description to 2.7, 3.4+.

Consider Circle CI + carthorse...

**Comment by cjw296** [comment]
https://pypi.org/project/mock/3.0.0/
