### ISSUE TITLE
side_effect should be checked for iterable not callable

### ISSUE THREAD

**Issue by jazzblue** [testing-cabal/mock#448]
https://github.com/testing-cabal/mock/blob/7a6ff3576274fb1627b4bd11d8e28eb51260a96b/mock/mock.py#L1115-L1116

This works correctly for iterables (such as lists) that are not defined as generators.
However, if one defined a generator as a function this would not work.

It seems like the check should be not for callable, but for iterable.

**Comment by tirkarthi** [comment]
This repo is only for backport related issues. Please report this upstream on https://bugs.python.org and a short code snippet of the expected and actual behavior will also help.

Thanks

**Comment by jazzblue** [comment]
OK, thanks, I have opened the issue:

[](https://bugs.python.org/issue36598)
