### ISSUE TITLE
drop jython support in 3.0.0?

### ISSUE THREAD

**Issue by cjw296** [testing-cabal/mock#453]
@rbtcollins / @mfoord / @voidspace - thoughts?

We have no CI for it, so it's likely to have bit-rotted...

**Comment by voidspace** [comment]
Without CI we can't guarantee it. As far as I recall it was no extra work, but unless someone will test/maintain it I'm happy to drop official support. (No idea how I ended up with two GitHub users.)

**Comment by cjw296** [comment]
Yeah, I can't find any official or support docker images for Jython, so...

**Comment by berkerpeksag** [comment]
+1 for dropping it. I've never run mock's test suite on Jython before, so I guess it may have already been broken.

**Comment by tirkarthi** [comment]
There is no straightforward to run tests in Jython from Travis like pypy as far as I have searched around. The only example was astroid that downloaded and built it themselves. They also removed it from their CI later. Jython also doesn't support Python 3 yet so I am not sure if it's worth the effort given Python 2 EoL.

https://github.com/PyCQA/astroid/commit/359118209ee5a458e83d5b137c2066447acdfd0d

**Comment by cjw296** [comment]
Well, I'm planning to move the backport to CircleCI for various reasons, so if we had a stable, publicly maintainer docker image, that would do it.

But, as you say, if they have no Py3, then I think we're safe to drop it.

**Comment by cjw296** [comment]
Okay, 'tis done, ed3bc8b.

**Comment by rbtcollins** [comment]
I don't think we should drop the Jython glue; it is platform checked to not affect other interpreters and has approx 0 maintenance overhead for us. The whole point of the backport is to make current mock features more widely available.

**Comment by cjw296** [comment]
Anyone who needs this can use 2.0.0 though, right?

**Comment by rbtcollins** [comment]
Kindof defeats the purpose of doing the backport is all. We can equally say
that folk can just use the mock in their Python interpreter's stdlib. We do
the backport to allow projects that use mock to use newer features without
having to mandate a very latest release of CPython; to a large degree we
should be driven by our users, and in this case its worth remembering that
we're a second order dependency: a project with developers or deployers
using Jython may depend on mock working there, without it enabling us to CI
it.

We'll know its broken if they report bugs, but we can't tell the difference
between 'not used' or 'working fine' with the feedback systems we have in
place today.

-Rob

**Comment by cjw296** [comment]
Totally agree, and if we see evidence of Jython users or Jython users complaining that things no longer work, we can very easily revert the one commit above and bring it back :-)

**Comment by rbtcollins** [comment]
Sure, I'll leave it with you; my bias is to not remove it in the first place, because then there's no interrupt to run around and un-break, but if you're up for that, all good.

**Comment by tirkarthi** [comment]
Not sure if this is the issue to discuss this but is it agreed upon to remove it in upstream unittest.mock too? I feel upstream CPython has a larger userbase. Though there are no signs of Python 3 support for Jython or CI in CPython for Jython I think removal could at the least have a NEWS entry/whatsnew/porting section entry.

**Comment by tirkarthi** [comment]
Sorry forgot to paste the merged PR link : https://github.com/python/cpython/pull/13033

**Comment by rbtcollins** [comment]
The upstream one gets copied into Jython when they update their stdlib, so
if its still needed at all, they'll still need it there. I see value in
keeping the delta low, so yeah, removing it upstream makes sense to me too.

-Rob
