### ISSUE TITLE
License file missing from sdist

### ISSUE THREAD

**Issue by jakirkham** [testing-cabal/mock#459]
Appears the license file is missing from the sdist in the recent release. Guess this is something pbr automated previously. Would it be possible to have the license file included in the future?

**Comment by cjw296** [comment]
Fixed in e1896ffa8f0afdd42fafdf654f5221036614f3d0.

**Comment by cjw296** [comment]
Release in 3.0.4.

**Comment by jakirkham** [comment]
Thanks @cjw296 !
