### ISSUE TITLE
Source tarball does not distribute tests

### ISSUE THREAD

**Issue by ngie-eign** [testing-cabal/mock#469]
Some upstream groups rely on the tests to provide a green light on whether or not a port or upgrade is worth performing.

mock has tests in git, but it doesn't make them available in the source project. Thus, there's no way to test the code without having a git checkout with the corresponding release tag.

[Example](https://reviews.freebsd.org/D21654): I needed to pull the sources from GitHub using the commit hash, instead of using the release tagged tarball.

**Comment by tirkarthi** [comment]
Does PR #468 solve this?

**Comment by cjw296** [comment]
Yep :-)
