### ISSUE TITLE
Add new mock features from Python 3.8

### ISSUE THREAD

**Issue by 5j9** [testing-cabal/mock#470]
In Python 3.8 `unittest.mock` has had some improvements. It would be nice to see them in this library. The two features that I am currently looking for are:
* `MagicMock` objects are now [awaitable](https://stackoverflow.com/questions/51394411/python-object-magicmock-cant-be-used-in-await-expression).
* `call` objects are now named tuples. See the example in [documentation](https://docs.python.org/3.8/library/unittest.mock.html#unittest.mock.call.call_list):

```python
>>> kall.kwargs is kall[1]
True
```

**Comment by tirkarthi** [comment]
At the core dev sprints I was part of a discussion on this. The upstream now contains several bug fixes along with new features like `AsyncMock` that makes it Python 3 only and there are syntax level changes like `async def` that make maintaining this backport to be Python 2 compatible along with keeping up with upstream. At some point maybe as Python 2 reaches end of life after January 1, 2020 there will be a backport of the bug fixes to make a final release. Then there will be a new release with this repo synced with upstream thus essentially dropping Python 2 support and becoming Python 3.5/3.6+ only. Thus users from 3.6 can install this backport and can use features like `AsyncMock` that are 3.8+ only.

**Comment by cjw296** [comment]
See https://github.com/testing-cabal/mock/pull/476, we can track there.
