### ISSUE TITLE
Mock 4.0.0 "missing X positional argument" on instantiation of objects inherited from mock.MagicMock

### ISSUE THREAD

**Issue by doublethefish** [testing-cabal/mock#480]
We have a test module that mocks tkinter items using mock.MagicMock. Using 4.0.0.

Since yesterday's update we have an issue instantiating magicmock descendant objects and even access members that are magicmock objects ( e.g. `assert _some_magic_mock_descendant`) - here we focus on the former as it's a simpler repro case.

### Minimal example
```
# mock tkinter
TKINTER_MODULE_NAME = "tkinter"
TKINTER_MOCK = types.ModuleType(TKINTER_MODULE_NAME)                                    sys.modules[TKINTER_MODULE_NAME] = TKINTER_MOCK                                         
class MockTkinterBase(mock.MagicMock):                  
TKINTER_MOCK.ttk = MockTkinterBase  
TKINTER_MOCK.Text = MockTkinterBase        
```

```
# import this after importing the above
import tkinter as tk   # pulls in the above


class UISelectionDebugInfo(tk.LabelFrame):                                              
     def __init__(self, parent):                                                         
         super().__init__(parent=parent, text="Debug")  # aok: all key-words explicit
                                                                                         
         self.text = tk.Text(self)  # fails: positional arg for parent
```

### Traceback of example error
```
Traceback (most recent call last):
  File "<...>test_canvas.py", line 40, in _create_canvas                                     
    canvas = UICanvas(parent=mock_tk.MockTkinterBase())                                        
  File "<...>tkinter/ui_canvas.py", line 101, in _ui_init_ui                                 
    self._debug_pane = UISelectionDebugInfo(parent=self)                                       
  File "<...>tkinter/ui_selection_debug_info.py", line 6, in __init__                        
    super().__init__(parent, text="Debug")                                                     
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 2077, in __init__               
    _safe_super(MagicMixin, self).__init__(*args, **kw)                                        
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 1085, in __init__               
    _spec_state, _new_name, _new_parent, **kwargs                                              
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 439, in __init__                
    self._mock_add_spec(spec, spec_set, _spec_as_instance, _eat_self)                          
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 494, in _mock_add_spec          
    if iscoroutinefunction(getattr(spec, attr, None)):                                         
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 522, in __get_return_value   
    _new_parent=self, _new_name='()'                                                           
  File "<...>lib/python3.7/site-packages/mock/mock.py", line 1027, in _get_child_mock        
    return klass(**kw)                                                                         
TypeError: __init__() missing 1 required positional argument: 'parent'
```

Orthogonally, we see that that there are comments in other issues on this github account that refer to https://bugs.python.org but it's not clear to us when/where that should be the case, nor whether it is worth our time creating a PR to help on this issue. We will log an issue to add contribution guidelines and maybe come back and help fix this at some point.

**Comment by cjw296** [comment]
https://mock.readthedocs.io/en/latest/#bug-reports is there and suggests this should be reported on https://bugs.python.org/. I suspect this might be a bug upstream related to use of `parent` in `UISelectionDebugInfo`.

However, there is a chance this is backport specific and related to the fact we had to skip https://github.com/python/cpython/commit/2085bd0877e17ad4d98a4586d5eabb6faecbb190 for positional-only arguments.

@tirkarthi - thoughts?

@doublethefish - are you able to reproduce this on either CPython master or one of the Python 3.9 alpha releases?

**Comment by doublethefish** [comment]
Thanks for the quick reply.

We are able to reproduce on Python 3.9.0a3 (OSX). When I jump back to my linux box I'll try it there too.

Here's another call-stack that shows the issue; this variant suggests that the `name` keyword on get_child_mock() is being passed to the tkinter class ctor.

At the end of the following stack `klass` is type `UISelectionDebugInfo` and kw has keys `dict_keys(['name', '_new_name', '_new_parent']))`.

```
 Traceback (most recent call last):
  File "<...>test_ui_selection_debug.py", line 14, in test_ctor
    debug_ui = self.object()
  File "<...>test_ui_selection_debug.py", line 11, in object
    return UISelectionDebugInfo(parent)
  File "<...>ui_selection_debug_info.py", line 8, in __init__
    self.text = tk.Text(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mock/mock.py", line 411, in __new__
    if spec_arg and _is_async_obj(spec_arg):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mock/mock.py", line 2160, in __get__
    return self.create_mock()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mock/mock.py", line 2153, in create_mock
    m = parent._get_child_mock(name=entry, _new_name=entry,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mock/mock.py", line 1026, in _get_child_mock
    return klass(**kw)
TypeError: __init__() got an unexpected keyword argument 'name'
```

It's not clear, yet, why __get__() is being called by the __init__()....

**Comment by cjw296** [comment]
Okay, thanks, this seems a clear indication it needs to be fixed upstream.
Please can you open an issue on https://bugs.python.org/?

It might be sufficient to link to this issue, but probably better to copy and paste.
If you wouldn't mind posting the https://bugs.python.org/ link to the issue once submitted, that would be great!

**Comment by cjw296** [comment]
(although, to be fair, the exceptions are slightly different between 3.9 and the backport...)

Still, we'd want to get the upstream issue fixed and then get things happy on the backport.

**Comment by doublethefish** [comment]
The exceptions are different because they're two different unittests. The exceptions are exactly the same for the same testcase for python3.7.mock (backport), python3.9a.mock (backport) and python3.9a.unittest.mock (upstream).

In the above tracebacks we were always using `mock` (backport) and not `unittest.mock` (upstream)... We've now properly tested with the upstream on python3.9a and the issue is exactly the same so will report there.

Thanks.

**Comment by cjw296** [comment]
Cool, please can you comment the bugs.python.org issue link on here once you've submitted it?

**Comment by doublethefish** [comment]
The main part of the issue observed is now logged:
https://bugs.python.org/issue39578

That issue purely looks at the problems associated with mocking associative-hierarchies such as you find in tkinter or qt. The other issues we thought we saw with member-variable/function access we'll log if there's time.
