### ISSUE TITLE
Please add contribution guidelines

### ISSUE THREAD

**Issue by doublethefish** [testing-cabal/mock#481]
We're unable to find the contribution guidelines. Please add contributing.md (or similar) or point us in the right direction to find them.

We would love to know how contribute and help.

**Comment by cjw296** [comment]
From https://mock.readthedocs.io/en/latest/#mock-mocking-and-testing-library: "mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.", so fixes go through CPython contributor process, unless they're specifically for the backport.

I think that's sufficient, but I'm not big on knowledge as to what the right way is to do more.
