### ISSUE TITLE
egg_info for package mock produced metadata for project name unknown

### ISSUE THREAD

**Issue by jturel** [testing-cabal/mock#486]
We're having issues in our project when building its test containers when installing mock per our test-requirements.txt:

```
flake8; python_version >= '2.7'
mock; python_version >= '2.7'
unittest2
```

Results in:
```
Collecting mock (from -r test-requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1c/fd/141c477591ab50e27cd16a4969c957f915f4fb3c6323a624c548f38b507f/mock-4.0.1.tar.gz (71kB)
    100% |################################| 81kB 6.3MB/s 
  Running setup.py (path:/tmp/pip-build-nxyrPI/mock/setup.py) egg_info for package mock produced metadata for project name unknown. Fix your #egg=mock fragments.
```

<snip>

```
Successfully installed argparse configparser entrypoints enum34 flake8 functools32 linecache2 mccabe pycodestyle pyflakes traceback2 typing unittest2 unknown                                                       

```
Notice the 'unknown' 

And when running the tests:

```
python2 test/unittest_suite.py                                                                            
Traceback (most recent call last):                                                                        
  File "test/unittest_suite.py", line 38, in <module>                                            
    map(__import__, modules)                                                                              
  File "/app/test/test_katello/test_enabled_report.py", line 4, in <module>                               
    from mock import patch                                                                                
ImportError: No module named mock 
```

Our project: https://github.com/Katello/katello-host-tools/
Reproduced by `make docker-test` target which defaults to a CentOS7 container

Seems to have happened with the 4.0.0 release. Let me know if I can provide any more useful information!

**Comment by cjw296** [comment]
This smells like https://github.com/testing-cabal/mock/issues/461.
What version of setuptools/pip are you using?

**Comment by jturel** [comment]
```
[root@f4f7463dc5e5 app]# rpm -q python-setuptools python python2-pip
python-setuptools-0.9.8-7.el7.noarch
python-2.7.5-76.el7.x86_64
python2-pip-8.1.2-10.el7.noarch
```

I was able to work around it by locking to mock < 4.0.0

Is it that my pip and/or setuptools are too old to work with mock now?

**Comment by cjw296** [comment]
Right, so Mock no longer supports Python 2, and those versions of pip and setuptools are really really ancient. You should be using setuptools 44 (45 dropped Py2 support) and pip 20. I suspect if you were using those, even on Python 2, they would have looked at the package metadata and kept your install on Python 2.

That said, looks like you're using docker images, in which case the system rpms for these aren't the right thing to use, why not use the official python images on docker hub?

**Comment by jturel** [comment]
It's fine for us to lock to an older mock version where we have older dependencies on EL7. Just wanted to make sure this wasn't a real issue that needed to be fixed in this repo. Thanks!

**Comment by cjw296** [comment]
Honestly, it's not fine to be on such ancient versions of pip and setuptools - they will cause you more problems like this, and some that might not be so apparent.
