### ISSUE TITLE
Allow a mock to pass an issubclass test or to be used as the second argument to isinstance (by providing __bases__)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#71]
```
For example:
{{{
>>> class foo(object):
...   @property
...   def __bases__(self):
...     return (int,)
... 
>>> a = foo()
>>> issubclass(a, int)
True
}}}
```

Original issue reported on code.google.com by `fuzzyman` on 1 Mar 2011 at 12:05

**Comment by cjw296** [comment]
@mfoord / @fuzzyman - did you ever make progress on this? Mocking out classes where there are `isinstance` checks involved is kinda painful :-/

**Comment by voidspace** [comment]
I didn't yet. I don't think it will be very hard. Hopefully I can do it in the PyCon sprints.

**Comment by voidspace** [comment]
Passing an issubclass check is very hard to mock out. 
For issubclass(bar, Foo) there's nothing you can do on bar or type(bar) (where bar is a mock object) to make it pass. You could mess with Foo to override `__subclasscheck__` but that's not what we want to achieve (and not possible if Foo is a built-in type).

Overriding issubclass is a better approach and you can already do that.
